env:
 - DATABASE_URL="postgres://postgres@localhost/deep_thought_development"

language: ruby

install: script/bootstrap

before_script: psql -c 'create database deep_thought_development;' -U postgres
script: script/test
